### PR TITLE
Three fixes around scrolling

### PR DESCRIPTION
**Pull request by avl42**
As it was, automatic refresh mode would have spoilt scroll optimization...
I think after-all this approach is even better than my changing default to DELTA.

PS: follow-up to #151 and #138

### CODE REVIEW

**Comment by avl42** [comment]
ok, wait a bit,   "three makes a charm"  ... third one arriving shortly...

**Comment by avl42** [comment]
Ok, this third one is a corner case: When the screen is clear()ed, then scrolling the terminal makes no sense until next refresh...

**Comment by avl42** [comment]
@mabe02, not noticed, yet, or just put off for later?

**Comment by mabe02** [comment]
Sorry, I missed this one

**Pull request merged**
