### PR TITLE
Refactor UnixTerminal and CygwinTerminal.

### PR DESCRIPTION
**Pull request by avl42**
This is my first throw at untangling CygwinTerminal from UnixTerminal.
It is based on Issue #139 which shows, that CygwinTerminal inherits more
from its base-class than it can handle.

I don't have cygwin anywhere near hand, so I'd appreciate someone with
cygwin to try it and report on it.

PS: I did run some of the terminal test-programs for UnixTerminal, and they looked fine to me under Linux.

### CODE REVIEW

**Comment by mabe02** [comment]
Looks ok, I'd like to try it out at home first with Cygwin before merging

**Comment by avl42** [comment]
Yes, under all circumstances, please test it with cygwin before merging to master!

Some remark: I wondered if stty's option -F would be available also for Unix, as that would easily allow skipping the shell, but while Linux's stty has it, unfortunately neither Solaris, nor AIX have it. It could still be possible, though, if stty's stdin could be redirected from /dev/tty in Java using the ProcessBuilder.

**Comment by avl42** [comment]
I wasn't sure, if Java on cygwin can simply open "/dev/pts0" and pass it to stty.exe as stdin, so I made the changes ineffective for CygwinTerminal. Rather let stty.exe on cygwin open its device itself.

Eventually a better name might be found for UnixishTerminal  ;-)

One more thing:  If a UnixTerminal-instance is created with no streams specified, then, instead of System.in/out, shouldn't it rather open "/dev/tty" for read&write and use those streams? That would enable it to work like the "less"-utility: getting data from stdin, but interacting using the tty...

**Comment by mabe02** [comment]
I've never thought of having it go directly to the tty, any particular benefit over using standard output?

**Comment by mabe02** [comment]
Never got a chance to try it out for real with Cygwin, but I liked the change in general so I'll take it as it is. Will do some more investigation over weekend. One of the gotchas with running Java on Cygwin that hit me over and over is that the Java executable isn't compiled with cygwin so all the unix emulation is unavailable. Hopefully if all cygwin commands are on the $PATH it should still work to call them, but I do remember some strangeness when trying to change certain parameters (echo?) that just wouldn't take effect.

**Comment by mabe02** [comment]
Renaming it to UnixLikeTerminal but not 100% happy with that either. Just that the usual AbstractUnixTerminal or BaseUnixTerminal or something like that doesn't appeal to me either. Open to suggestions...

**Pull request merged**
