### PR TITLE
Menus

### PR DESCRIPTION
**Pull request by BrunoEberhard**
based on the work of fracpete but I wanted to have sub menus.

Also I wanted to iterate over the menu entries with characters

### CODE REVIEW

**Comment by buko** [comment]
Out of curiosity why doesn't this PR get merged?

**Comment by avl42** [comment]
most likely because @mabe02 is busy in real life...

**Comment by mabe02** [comment]
Yeah, pretty much it :)

**Comment by mabe02** [comment]
We need to review the themes though, I'm pretty sure most of them don't look very pretty now since the menu component is extending button (and hence gets the button theme)

**Pull request merged**
