### PR TITLE
Resizing SwingTerminalFrame wont grow the terminal #326

### PR DESCRIPTION
**Pull request by klaushauschild1984**
Here is a minimal test case for the resizing.
And it works!

### CODE REVIEW

**Comment by mabe02** [comment]
I tried it but it works fine for me. When I resize the window, the terminal grows and the terminal size is printed in the top-left corner... (Windows 10)

**Comment by avl42** [comment]
Same for me.   The displayed text updates well as I'm dragging the Window borders.

@klaushauschild1984 , if this problem has disappeared for you, then please close the issue and this PR.
otherwise let us know. After all, two years have passed since.

**Comment by avl42** [comment]
update: the issue 326 was closed two years ago, only this PR was apparently forgotten.

**Comment by mabe02** [comment]
Alright, closing...

**Pull request closed without merging**
