### PR TITLE
Table component - add support for PgUp and PgDn

### PR DESCRIPTION
**Pull request by MartyIX**
Hi,

This is a proposed PR for #387 issue. What do you think?

Regards,
Martin

### CODE REVIEW

**Comment by mabe02** [comment]
Looks good to me, thanks!

**Comment by MartyIX** [comment]
@mabe02 There is one thing that is not solved. When client code does not set `setVisibleRows(num)`, then PgUp & PgDn do not work. It's because I'm not sure how to obtain the number of visible rows in that case.  

I must say that `visibleRows` field is a bit confusing to me. I would expect that it always contain value that corresponds witht what user can see.

**Comment by mabe02** [comment]
If you don't set this value, the table will request to be large enough to display all the rows. If the terminal window isn't large enough to support this, the size will ultimately be decided based on how many rows does fit.

**Comment by mabe02** [comment]
Okay, a couple of hours later I've re-written half of the table and while it solves the problems above it's probably got a million other bugs. I've put it on master for now. For 3.0, I think we're going to have to admit that PageUp and PageDown won't work for tables that are not vertical size restricted. The scrolling doesn't work properly anyway so there wouldn't be much point in trying to fix the paging.

**Comment by MartyIX** [comment]
@mabe02 
> Okay, a couple of hours later I've re-written half of the table and while it solves the problems above it's probably got a million other bugs. I've put it on master for now. 

Great 👍 

> The scrolling doesn't work properly anyway so there wouldn't be much point in trying to fix the paging.

How do you mean?

**Pull request merged**
