### PR TITLE
AutoCloseable for telnet classes

### PR DESCRIPTION
**Pull request by LTI2000**
Hi, I propose a change which lets you use TelnetTerminal and TelnetTerminalServer in try-with-resources blocks.

### CODE REVIEW

**Comment by dant3** [comment]
This breaks Java 1.6 compatibility

**Comment by LTI2000** [comment]
We have Java 8, java 7 is already end of life

**Comment by avl42** [comment]
It might be easy to upgrade Java on a PC, but it is far not so easy to upgrade it on certain Unix machines (e.g. AIX), whose vendors offer their own Java port.  I'm in the (relatively) "lucky" situation, that the machines to run my programs already have Java 7 on them, but I know it will take a long time, even now that Java 7 is officially "end of life", that I'll get to see a Java 8 (then probably on new hardware only).  I guess the situation isn't better for people stuck with Java 6 on some platform.

No doubt, there will some day be a point where dropping Java 6 is justified, but (imho) "AutoClosable" isn't such a point, not even ProcessBuilder.redirectInput.

One in a Java7/8 environment can create a subclass of those telnet classes, and have the subclass implement AutoClosable, if try-with-ressources is more than a convenience.

**Comment by mabe02** [comment]
Yes, lanterna 3 will remain JDK 6 compatible

**Pull request closed without merging**
